### ISSUE TITLE
Theming is not working at all? md-accent, md-hue?

### ISSUE THREAD

**Issue by d668** [sovanna/angular-material-sidenav#29]
I tried some md-accent, md-hue and seems like "primary" is just hardcoded?

**Comment by sovanna** [comment]
Yes it is.

If you look at [https://material.angularjs.org/latest/Theming/01_introduction](url) about the **Colors Intentions** _primary - used to represent primary interface elements for a user_

So, for this main menu on interface, it intends to be a **primary interface**, that's why md-accent can not work.

About the hue, I've respected the original menu from Angular, so I've used primary.800 and so on.
If needed, you change change the theming with $mdThemingProvider.
See [https://material.angularjs.org/latest/Theming/03_configuring_a_theme](url)
